version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  ai-service:
    build:
      context: ./tuya-ai
    container_name: python-ai
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend:
    build:
      context: ./smart-home-backend
    container_name: java-backend
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - TUYA_ACCESS_ID=${TUYA_CLIENT_ID}
      - TUYA_ACCESS_SECRET=${TUYA_CLIENT_SECRET}
      - TUYA_REGION=${TUYA_REGION}

    depends_on:
      - mongodb
      - ai-service
    restart: unless-stopped

  frontend:
    build:
      context: ./tuya-frontend
    container_name: react-frontend
    ports:
      - "3030:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data: