connector.ak=5uem3y9sqtx3hcc4r7xt
connector.sk=faf18b976f644363bcfe5a18ec4a35de
connector.region=EU
spring.data.mongodb.uri=mongodb://localhost:27017/tuya_iot
logging.level.com.tuya.connector.open.messaging=DEBUG