#connector.ak=${TUYA_ACCESS_ID}
#connector.sk=${TUYA_ACCESS_SECRET}
connector.ak=5uem3y9sqtx3hcc4r7xt
connector.sk=b6037c552bf14a04a359d3a6f30b9c7e
connector.region=EU
spring.data.mongodb.uri=mongodb://localhost:27017/tuya_iot
logging.level.com.tuya.connector.open.messaging=DEBUG